GET http://localhost:3000/api/mp/users

###
POST http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM

###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM

###
DELETE http://localhost:3000/api/mp/users/6ff41660-bd68-11ee-bcda-f7fbaddaccc3









###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums
Content-Type: application/json

{
  "type": "createdAlbums"
}

###
POST http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums
Content-Type: application/json

{
  "type": "createdAlbums"
}

###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/b50697d0-b9c8-11ee-8789-3b2184ec8f13
Content-Type: application/json

{
  "type": "createdAlbums"
}

###
DELETE http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/aed5d470-bcac-11ee-a597-6d4fa5b50ee6
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
PUT http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/a41e5b10-b9eb-11ee-b4b3-2d148b4ee929
Content-Type: application/json

{
  "type": "createdAlbums",
  "title": "9月",
  "subTitle": "23日·舟山"
}








###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/267d0870-bccd-11ee-953b-cf858a01557b/pictures
Content-Type: application/json

{
  "type": "createdAlbums"
}

###
POST http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/348b7ad0-bcb6-11ee-bfef-df9baa23f9a5/pictures
Content-Type: multipart/form-data

{
  "type": "createdAlbums"
}

###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/b50697d0-b9c8-11ee-8789-3b2184ec8f13/pictures/680c5650-b9cc-11ee-9c1f-5bc4d56db4b5
Content-Type: application/json

{
  "type": "createdAlbums"
}

###
DELETE http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/b11e7060-bd66-11ee-bcda-f7fbaddaccc3/pictures/6ff41660-bd68-11ee-bcda-f7fbaddaccc3
Content-Type: application/json

{
  "type": "createdAlbums"
}













###
GET http://localhost:3000/user
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg

###

DELETE http://localhost:3000/user
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg

###

GET http://localhost:3000/user/pictures
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjgyMDY3MDQ0fQ.YDZkYk67xIrf78WmRHXTVrSSBZkRSLy9-0pyf4jg7xM

###

POST http://localhost:3000/user/pictures
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NTQ0NzY2fQ.F-uf9TJUmMx9vFgwleSGRiU4QMqv5nDjKYrEDC7KacA
Content-Type: application/json

{
  "url": "url3",
  "timeStamp": "now2",
  "description": "demo2"
}

###

GET http://localhost:3000/user/pictures/1b6cb4e0-9d10-11ed-8afa-69f41af5ce2c
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg

###

DELETE http://localhost:3000/user/pictures/3c049fa0-9cd0-11ed-b788-6991ccc9fd5f
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg