GET http://localhost:3000/api/mp/users

###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM

###
DELETE http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM

###
POST http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM







###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
POST http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/0e14fe90-b93b-11ee-bcba-7f0eaa16b1ec
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
DELETE http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/7e9b8170-b940-11ee-bdc1-67b8ceeff37c
Content-Type: application/json

{
  "type": "sharedAlbums"
}






###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/2ef6ed90-b99e-11ee-8e87-4590f86b3837/pictures
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
POST http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/2ef6ed90-b99e-11ee-8e87-4590f86b3837/pictures
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
GET http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/2ef6ed90-b99e-11ee-8e87-4590f86b3837/pictures/b4f09210-b9b8-11ee-8cee-7d0c9b3c095d
Content-Type: application/json

{
  "type": "sharedAlbums"
}

###
DELETE http://localhost:3000/api/mp/users/oHya266aR6YbGmbD8v8OYi0kfJEM/albums/2ef6ed90-b99e-11ee-8e87-4590f86b3837/pictures/f1051ff0-b9b8-11ee-bea0-134f57d27847
Content-Type: application/json

{
  "type": "sharedAlbums"
}













###
GET http://localhost:3000/user
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg

###

DELETE http://localhost:3000/user
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg

###

GET http://localhost:3000/user/pictures
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjgyMDY3MDQ0fQ.YDZkYk67xIrf78WmRHXTVrSSBZkRSLy9-0pyf4jg7xM

###

POST http://localhost:3000/user/pictures
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NTQ0NzY2fQ.F-uf9TJUmMx9vFgwleSGRiU4QMqv5nDjKYrEDC7KacA
Content-Type: application/json

{
  "url": "url3",
  "timeStamp": "now2",
  "description": "demo2"
}

###

GET http://localhost:3000/user/pictures/1b6cb4e0-9d10-11ed-8afa-69f41af5ce2c
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg

###

DELETE http://localhost:3000/user/pictures/3c049fa0-9cd0-11ed-b788-6991ccc9fd5f
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcGVuSUQiOiJvTVp6WjRxb3oxT0JaNEduaEZNNG93ODJiZnVjIiwiaWF0IjoxNjc0NDQ2MDI5fQ.gfi4yg8C62xdgbmKQsFhIi6AeV4Jlm0NEp8DhmV43Cg